apiVersion: v2
name: multi-cloud-devsecops
description: A Helm chart for Multi-Cloud DevSecOps FastAPI application
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - fastapi
  - multi-cloud
  - devsecops
maintainers:
  - name: DevOps Team
    email: devops@example.com
